package ec.edu.espe.contactbook.view;

import ec.edu.espe.contactbook.model.Contact;
import ec.edu.espe.contactbook.model.Sport;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author LABS-ESPE
 */
public class FrmContact extends javax.swing.JFrame {

    int id = 0;

    /**
     * Creates new form FrmContact
     */
    public FrmContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnlContactTitel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlContactsInput = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtCellphoneNumber = new javax.swing.JTextField();
        cmbFrequentFriend = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        cmbType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaComments = new javax.swing.JTextArea();
        txtBirthDate = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSports = new javax.swing.JList<>();
        PnlContactsBotons = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Contacts");

        javax.swing.GroupLayout PnlContactTitelLayout = new javax.swing.GroupLayout(PnlContactTitel);
        PnlContactTitel.setLayout(PnlContactTitelLayout);
        PnlContactTitelLayout.setHorizontalGroup(
            PnlContactTitelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactTitelLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlContactTitelLayout.setVerticalGroup(
            PnlContactTitelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactTitelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jLabel2.setText("id:");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Cell phone:");

        jLabel6.setText("Email:");

        jLabel7.setText("Frequent Friend:");

        jLabel8.setText("Type:");

        jLabel9.setText("Birth Date:");

        jLabel10.setText("Comments:");

        jLabel11.setText("Sports:");

        txtid.setToolTipText("Only digitis are entered here, for example 0111");
        txtid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtidFocusLost(evt);
            }
        });

        txtFirstName.setToolTipText("");

        cmbFrequentFriend.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        cmbFrequentFriend.setToolTipText("Ye if your friends send this message");

        txtEmail.setToolTipText("emails format: new@company");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Friend", "Family", "Job", "University" }));

        txaComments.setColumns(20);
        txaComments.setRows(5);
        jScrollPane1.setViewportView(txaComments);

        lstSports.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Soccer", "Football", "Basketball", "Baseball", "Tennis", "Swimming", "Volley" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstSports);

        javax.swing.GroupLayout PnlContactsInputLayout = new javax.swing.GroupLayout(PnlContactsInput);
        PnlContactsInput.setLayout(PnlContactsInputLayout);
        PnlContactsInputLayout.setHorizontalGroup(
            PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactsInputLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PnlContactsInputLayout.createSequentialGroup()
                        .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(cmbFrequentFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)
                            .addComponent(txtCellphoneNumber))
                        .addGap(98, 98, 98)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        PnlContactsInputLayout.setVerticalGroup(
            PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactsInputLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlContactsInputLayout.createSequentialGroup()
                        .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtCellphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbFrequentFriend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(PnlContactsInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnlContactsBotonsLayout = new javax.swing.GroupLayout(PnlContactsBotons);
        PnlContactsBotons.setLayout(PnlContactsBotonsLayout);
        PnlContactsBotonsLayout.setHorizontalGroup(
            PnlContactsBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactsBotonsLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PnlContactsBotonsLayout.setVerticalGroup(
            PnlContactsBotonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlContactsBotonsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnSave)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlContactTitel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlContactsInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PnlContactsBotons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PnlContactTitel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlContactsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnlContactsBotons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String firstName;
        String lastName;
        String celphoneNumber;
        String email;
        boolean frequentFriend;
        String type; //family, friend, job, university
        Calendar bornOnType;
        String comments;
        ArrayList<Sport> sports = new ArrayList<>();
        Contact contact;

        validateNumbersInId();

        validateFirstName();

        validLastName();

        validateCellPhone();

        validateEmail();

        validateBirthDate();

        validateComments();

        //id = Integer.parseInt(txtid.getText());
        firstName = txtFirstName.getText();
        lastName = txtLastName.getText();
        celphoneNumber = txtCellphoneNumber.getText();
        email = txtEmail.getText();
        frequentFriend = cmbFrequentFriend.getSelectedItem() == "Yes";
        type = cmbType.getSelectedItem().toString();
        bornOnType = Calendar.getInstance();
        comments = txaComments.getText();

        contact = new Contact(id, firstName, lastName, celphoneNumber, email, frequentFriend, type, bornOnType, comments, sports);

        JOptionPane.showMessageDialog(rootPane,
                "New Contact" + contact);

        JOptionPane.showMessageDialog(rootPane, lstSports.getSelectedValues());
    }//GEN-LAST:event_btnSaveActionPerformed

    public void validateComments() throws HeadlessException {
        try {
            if (txaComments.getText().length() > 200) {
                throw new Exception("El comentario no puede exceder los 200 caracteres");
            }
            txaComments.setForeground(Color.BLACK);
        } catch (Exception ex) {
            txaComments.setForeground(Color.RED);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error en Comentario", JOptionPane.ERROR_MESSAGE);
            txaComments.requestFocusInWindow();
        }
    }

    public void validateBirthDate() throws HeadlessException {
        try {
            if (txtBirthDate.getText().trim().isEmpty()) {
                throw new Exception("La fecha de nacimiento no puede estar vacía");
            }
            if (!txtBirthDate.getText().matches("^(0[1-9]|[12][0-9]|3[01])/(0[1-9]|1[0-2])/\\d{4}$")) {
                throw new Exception("Formato de fecha inválido. Use dd/mm/aaaa");
            }
            txtBirthDate.setForeground(Color.BLACK);
        } catch (Exception ex) {
            txtBirthDate.setForeground(Color.RED);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error en Fecha", JOptionPane.ERROR_MESSAGE);
            txtBirthDate.requestFocusInWindow();
        }
    }

    public void validateEmail() throws HeadlessException {
        try {
            if (txtEmail.getText().trim().isEmpty()) {
                throw new Exception("El email no puede estar vacío");
            }
            if (!txtEmail.getText().matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
                throw new Exception("Formato de email inválido. Ejemplo: usuario@dominio.com");
            }
            txtEmail.setForeground(Color.BLACK);
        } catch (Exception ex) {
            txtEmail.setForeground(Color.RED);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error en Email", JOptionPane.ERROR_MESSAGE);
            txtEmail.requestFocusInWindow();
        }
    }

    public void validateCellPhone() throws HeadlessException {
        try {
            if (txtCellphoneNumber.getText().trim().isEmpty()) {
                throw new Exception("El teléfono no puede estar vacío");
            }
            if (!txtCellphoneNumber.getText().matches("\\d{10}")) {
                throw new Exception("El teléfono debe contener exactamente 10 dígitos");
            }
            txtCellphoneNumber.setForeground(Color.BLACK);
        } catch (Exception ex) {
            txtCellphoneNumber.setForeground(Color.RED);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error en Teléfono", JOptionPane.ERROR_MESSAGE);
            txtCellphoneNumber.requestFocusInWindow();
        }
    }

    public void validLastName() throws HeadlessException {
        try {
            if (txtLastName.getText().trim().isEmpty()) {
                throw new Exception("El apellido no puede estar vacío");
            }
            if (!txtLastName.getText().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]{2,}")) {
                throw new Exception("El apellido solo puede contener letras y espacios (mínimo 2 caracteres)");
            }
            txtLastName.setForeground(Color.BLACK);
        } catch (Exception ex) {
            txtLastName.setForeground(Color.RED);
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error en Apellido", JOptionPane.ERROR_MESSAGE);
            txtLastName.requestFocusInWindow();
        }
    }

    public void validateFirstName() throws HeadlessException {
        try {

            if (txtFirstName.getText().trim().isEmpty()) {
                txtFirstName.setForeground(Color.RED);
                throw new Exception("El nombre no puede estar vacío");
            }

            if (!txtFirstName.getText().matches("[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]{2,}")) {
                txtFirstName.setForeground(Color.RED);
                throw new Exception("Nombre inválido. Solo letras y espacios, mínimo 2 caracteres");
            }

            txtFirstName.setForeground(Color.BLACK);

        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error en Nombre", JOptionPane.ERROR_MESSAGE);
            txtFirstName.requestFocus();
        }
    }

    private void txtidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtidFocusLost
        validateNumbersInId();
        validateFirstName();
        validLastName();
        validateCellPhone();
        validateEmail();
        validateBirthDate();
        validateComments();
    }//GEN-LAST:event_txtidFocusLost

    public void validateNumbersInId() throws HeadlessException {
        // TODO add your handling code here:

        try {
            id = Integer.parseInt(txtid.getText());
            txtid.setForeground(Color.black);
        } catch (NumberFormatException ex) {
            txtid.setForeground(Color.red);
            JOptionPane.showMessageDialog(rootPane, "please enter digit in the contact id", "Error on Id", JOptionPane.ERROR_MESSAGE);
            txtid.requestFocusInWindow();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContact.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContact.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContact.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContact.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlContactTitel;
    private javax.swing.JPanel PnlContactsBotons;
    private javax.swing.JPanel PnlContactsInput;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbFrequentFriend;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstSports;
    private javax.swing.JTextArea txaComments;
    private javax.swing.JTextField txtBirthDate;
    private javax.swing.JTextField txtCellphoneNumber;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
